language: node_js
node_js: 
  - stable
  - 8
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: './storybook-static'
  github_token: $GITHUB_TOKEN 
  on:
    branch: master
